Aviva.FizzBuzzDemo/Aviva.FizzBuzzDemo/Models/DisplayListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Aviva.FizzBuzzDemo.Models
{
    public class DisplayListModel
    {
        /// <summary>
        /// Gets or sets the list values.
        /// </summary>
        public List<string> ListValues { get; set; }
    }
}

Aviva.FizzBuzzDemo/Aviva.FizzBuzzDemo/Models/InputValuesModel.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="InputValuesModel.cs" company="Aviva">
//   Aviva
// </copyright>
// <summary>
//   The input values model.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Aviva.FizzBuzzDemo.Models
{
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// The input values model.
    /// </summary>
    public class InputValuesModel
    {
        /// <summary>
        /// Gets or sets the input number.
        /// </summary>
        [Required(ErrorMessage = "Please enter values")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "only integers allowed")]
        [Range(1, 1000, ErrorMessage = "Value should be between 1 and 1000")]
        [Display(Name = "Enter a number")]
        public int Number { get; set; }
    }
}

Aviva.FizzBuzzDemo/Aviva.FizzBuzzDemo/Controllers/InputValuesController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="InputValuesController.cs" company="Aviva">
//   Aviva
// </copyright>
// <summary>
//   Defines the InputValuesController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Aviva.FizzBuzzDemo.Controllers
{
    using System.Web.Mvc;
    using Aviva.FizzBuzzDemo.BusinessLogic;
    using Aviva.FizzBuzzDemo.Models;

    /// <summary>
    /// The input values controller.
    /// </summary>
    public class InputValuesController : Controller
    {
        /// <summary>
        /// The display list Model.
        /// </summary>
        private readonly DisplayListModel displayListModel = new DisplayListModel();

        /// <summary>
        /// The Interface for fizzbuzzlogic
        /// </summary>
        private readonly IFizzBuzzLogic fizzbuzzlogic;

        /// <summary>
        /// Initializes a new instance of the <see cref="InputValuesController"/> class.
        /// </summary>
        /// <param name="fizzbuzzlogic">
        /// The fizzbuzzlogic
        /// </param>
        public InputValuesController(IFizzBuzzLogic fizzbuzzlogic)
        {
            this.fizzbuzzlogic = fizzbuzzlogic;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InputValuesController"/> class.
        /// </summary>
        public InputValuesController() : this(new FizzBuzzLogic())
        {
        }

        /// <summary>
        /// The index.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Index()
        {
            return View("Index");
        }

        /// <summary>
        /// The display fizz buzz list.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        public ActionResult DisplayFizzBuzzList(InputValuesModel model)
        {
            this.displayListModel.ListValues = this.fizzbuzzlogic.GetIntegersList(1, model.Number);
            return View("DisplayFizzBuzzList", this.displayListModel);
        }

    }
}

Aviva.FizzBuzzDemo/Aviva.FizzBuzzDemo/Views/InputValues/DisplayFizzBuzzList.cshtml
@using Aviva.FizzBuzzDemo.Views
@model Aviva.FizzBuzzDemo.Models.DisplayListModel

@{
    ViewBag.Title = "DisplayFizzBuzzList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FizzBuzz List</h2>

@section Styles {
    <link href="@Url.Content("~/Content/FizzBuzzStyle.css")" rel="stylesheet" type="text/css" />
}

@foreach (var item in Model.ListValues.ToList())
{
    <div class="@FizzBuzzHelper.GetCssClassForFizzBuzz(item)">@item</div>
}

<div>
    @Html.ActionLink("Back to Input", "Index", "InputValues")
</div>

Aviva.FizzBuzzDemo/Aviva.FizzBuzzDemo/Views/InputValues/Index.cshtml
@model Aviva.FizzBuzzDemo.Models.InputValuesModel

@{
   Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("DisplayFizzBuzzList", "InputValues", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>InputValuesModel</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.Number)
                @Html.TextBoxFor(m => m.Number)
                @Html.ValidationMessageFor(m => m.Number)
            </li>
        </ol>
        <p>
            <input type="submit" value="Print List" />
        </p>
    </fieldset>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aviva.FizzBuzzDemo/Aviva.FizzBuzzDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    
                </div>
            </div>
        </footer>
        
        @Styles.Render("~/Content/css")
        @RenderSection("Styles", false)

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>